version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      # - .:/chat-nest/src/app
      - .:/chat-nest/src/app
      # - /chat-nest/src/app/node_modules/ # anonymous volume to avoid overriding node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      HOST: db
      PASSWORD_SQL: password
      PORT_SQL: 5432
      USERNAME_SQL: user
      NODE_ENV: development
      SALT: 10
      JWT_SECRET: FDFDV$V$v43v3v3434434F4343V33XE
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432
    
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
