version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./ # path that include docker file
      target: development #only build this image from dockerfile
      # volumes reflect changes in local machine to container directory and vise versa
    volumes:
      - ./:/chat-nest/src/app
      - /chat-nest/src/app/node_modules #anonymus volume
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
        DATABASE_URL: postgres://user:password@postgres:5432/db
        NODE_ENV: development
        PORT: 3000 #this is env variable
    ports:
      - 3000:3000
      - 9229:9229

   # Our Postgres Database for NestJS to connect to
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432
    
  # The Postgres Admin tool if we want to run some custom queries and so on against our Database  
  postgres_admin:
    image: dpage/pgadmin4:4.28 #This image is a pre-built Docker image for pgAdmin 4, a web-based administration tool for PostgreSQL.
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80

